### ISSUE TITLE
SVG menu items don't have a border stroke

### ISSUE THREAD

**Issue by benjaoming** [mirroringplaces/mirroringplaces.online#10]
Would be nice with a white or green outline?

![image](https://github.com/mirroringplaces/mirroringplaces.online/assets/374612/2b3aeeef-0867-4c60-a050-48944f96795f)

**Comment by johanne-aarup-hansen** [comment]
Jeg skal nok lave nogle nye filer med både hvid og grøn stroke, vender tilbage...
