### ISSUE TITLE
Set up custom URL in HoloLink

### ISSUE THREAD

**Issue by johanne-aarup-hansen** [mirroringplaces/mirroringplaces.online#108]
Hey Balder
Jeg skal bruge nogle URLs til HoloLink.
Tænker noget ala:
mirroringplaces.online/well
mirroringplaces.online/prisma
mirroringplaces.online/antenna
mirroringplaces.online/theend

Skal du hjælpe mig med det igennem din domain provider, eller kan jeg selv gøre det på en måde?

**Comment by benjaoming** [comment]
Hvad skal der ske på disse URL'er? Skal de pege på en anden URL?

(det er ikke på domæne, niveau, at man styrer stien i URL, det er serveren som domænet peger på, der håndterer stien)

**Comment by johanne-aarup-hansen** [comment]
Hey
Jeg skal bruge urlerne i HoloLink, så jeg kan generer en QRkode der ikke lige pludelig kan ændres. Lige nu bruger jeg bare HoloLinks generede url, men hvis der sker noget med programmet kan den godt ændre sig...

**Comment by johanne-aarup-hansen** [comment]
Er også i kontakt med HoloLInk, så vendt med at gøre noget, hvis jeg bare kan gøre det indenfor deres space. Så du ikke laver unødigt arbejde:)

**Comment by johanne-aarup-hansen** [comment]
Hej Balder
Jeg har fået et til at virke uden din hjælp. Så alt er godt:)
