### ISSUE TITLE
HTML structure and header issues

### ISSUE THREAD

**Issue by johanne-aarup-hansen** [mirroringplaces/mirroringplaces.online#19]
Hej Balder
Jeg synes der lidt noget galt med strukturen på de forskellige sider, men jeg kan ikke finde ud af hvad og hvor problemet ligger:
Headeren på hver side skal selvfølgelig gå helt ud til begge sider af containeren, men det er som om scrollbaren er i vejen.
Måske er det ikke containeren som der skal laves en param på, men på main? og så er det main at scroll funktionen skal kobles på?
Hvad tænker du?

**Comment by johanne-aarup-hansen** [comment]
Fx. kommer det til udtryk ved at der er problemer med at lægge padding på alle siderne... Du kan se det på about siden

**Comment by benjaoming** [comment]
Det har jeg også lagt mærke til. Jeg skal nok prøve at fikse det. Kan være, at "position: sticky" kan bruges, hvis headeren bliver en del af .container

**Comment by benjaoming** [comment]
Det lader til at fungere fint med "sticky" på headeren, men det fungerede ikke så godt for menuen i bunden, det finder jeg lige ud af.
