### ISSUE TITLE
Website visuralition on phone _ the menus and the frames are bleeding from screen

### ISSUE THREAD

**Issue by rodrigoandreolli** [mirroringplaces/mirroringplaces.online#25]
![1716371411406](https://github.com/mirroringplaces/mirroringplaces.online/assets/170082689/f215f86c-c194-46d4-ae1a-978740b4bc14)
![1716371411406](https://github.com/mirroringplaces/mirroringplaces.online/assets/170082689/dbd023eb-236e-4c38-a105-097a53559621)

**Comment by benjaoming** [comment]
Hey @rodrigoandreolli - there are things that aren't finished yet, looking at the ASAP :)
