### ISSUE TITLE
Adjust container for different screens

### ISSUE THREAD

**Issue by johanne-aarup-hansen** [mirroringplaces/mirroringplaces.online#30]
Hi Balder
There is still something wrong with the container size or it has to be adjusted, because on my screen it looks like this:

<img width="1440" alt="Screenshot 2024-05-22 at 13 52 33" src="https://github.com/mirroringplaces/mirroringplaces.online/assets/61514420/845459e2-0773-4494-b685-83aed129e5ed">

**Comment by benjaoming** [comment]
Sorry, I wasn't aware of the height constraint, so it was made to fill up the vertical space.

I'll make a change so the container's height becomes fixed and vertically centered.
