### ISSUE TITLE
Fit menu items to container

### ISSUE THREAD

**Issue by johanne-aarup-hansen** [mirroringplaces/mirroringplaces.online#57]
Hi Balder

Der er stadig problemer med at menuknapperne ikke passer til containeren.
Du kan se screenshots fra min labtop og min telefon:
<img width="1440" alt="Screenshot 2024-05-27 at 09 10 12" src="https://github.com/mirroringplaces/mirroringplaces.online/assets/61514420/dbd53609-94f6-4503-a4be-922058ebc669">
![Screenshot_20240527-091034](https://github.com/mirroringplaces/mirroringplaces.online/assets/61514420/72e341a8-302d-48dd-8abe-4664bbe7dd4b)

**Comment by benjaoming** [comment]
Det har jeg svært ved at genskabe. Kan du sige noget om, hvordan/hvornår det sker?

**Comment by johanne-aarup-hansen** [comment]
Det ser hele tiden sådan ud. Altså på min mobil kan man kun se lidt af knapperne og på min labtop går de ud over containeren og gør at man kan scrolle til horisontalt...

**Comment by benjaoming** [comment]
Yeeees okay, nu fandt jeg ud af det. Har åbenbart været et problem med nogle bestemte dimensioner. Jo bredere skærmen blir ift. højden, jo smallere blir containeren. Så hvis man f.eks. har en skærm, der er 600 px høj og gør den bredere, så begynder fejlen fra >950px.

Jeg retter lidt i CSS :+1: 

![image](https://github.com/mirroringplaces/mirroringplaces.online/assets/374612/40ef6717-fd7c-44ae-b8b2-a299b2456084)

**Comment by benjaoming** [comment]
Jeg tror ikke helt, at 9:16 er det egentlig format på en mobil, eftersom der forsvinder noget plads i toppen og bunden af mobilen til dens egen menu og navigation... det kan måske gøres lidt bedre ved at trimme noget af det tomme område i toppen af kortet væk, så det hele kan ses på mobil.

**Comment by johanne-aarup-hansen** [comment]
Hej Balder
Der er stadig problemer med menuen på mobiletelefonen. Der ser det stadig ud, som på billedet ovenfor

**Comment by benjaoming** [comment]
Hey!

Jeg kan stadig ikke genskabe det lokalt; men jeg har oprettet en konto på BrowserStack.

Kan du sige hvilken opløsning, din tlf kører?
