### ISSUE TITLE
Change of structure

### ISSUE THREAD

**Issue by johanne-aarup-hansen** [mirroringplaces/mirroringplaces.online#58]
Hej Balder
Er det muligt at du kan lave lidt om i strukturen på siden:

1. Jeg har snakket med Rodrigo om at det er bedre at story-siden bliver forsiden og map-siden bliver map-side. Kan du ordne det?
2. Jeg er også lidt forvirret omkring map-siden og scene-siden, eller for mig er det to forskellige ting, men programmeringsmæssigt står det som det samme, altså scene-sider. Igen har vi Rodrigo og mig lavet lidt om i strukturen, måske er det bare af navn, måske skal det have programmeringskonsekvenser. Det må du fortælle mig? Men for mig er kortet en kort/map-side og derigennem har man adgang til det som jeg før har kaldt scener, men nu hedder chapters. Kapitlerne kommer så til at bestå a forskellige scener nr 1 og 2 og 3 mm.
3. Navigationsmenuen i de nye kapitler fungere ikke helt... kan vi snakke om det?

**Comment by benjaoming** [comment]
Hvad er et objekt i forhold til alt dette? Altså f.eks. soccer shoes?

**Comment by johanne-aarup-hansen** [comment]
Her er indholdsfortegnelsen på historien:
Chapter : The beginning (det er story-siden)
Chapter Well-uni-code
- Scene 1
- Scene 2
- Scene 3
- Scene 4
- Scene 5
- Scene 6
Chapter Prisma-uni-code:
- Scene 7-12
Chapter Antenna-uni-code:
- Scene 13-18
Chapter 10: The End

En scene består af et objekt med tilhørende tekst.

Du kan også se en nogenlunde oversigt her:
https://docs.google.com/spreadsheets/d/1oebWRn6Yz6GHqhq-m05AVUayW8obwHy3_fclO-K5B8o/edit#gid=0
