### ISSUE TITLE
3d objects for scene 12, 13, 17, 24 missing

### ISSUE THREAD

**Issue by benjaoming** [mirroringplaces/mirroringplaces.online#64]

**Comment by johanne-aarup-hansen** [comment]
Der er genrelt nogle fejl i hvor hvilke objekter er, specielt i kapitel Antenna

**Comment by johanne-aarup-hansen** [comment]
Hvor er det nu jeg skal lægge filerne hen på github? Kan lægge dem ind imorgen eller nu, men ved bare ikke hvor:)

**Comment by benjaoming** [comment]
De ligger alle her: https://github.com/mirroringplaces/mirroringplaces.online/tree/main/static/3dmodels

**Comment by johanne-aarup-hansen** [comment]
Taaak, nu er objekter lige om lidt uploadet

**Comment by benjaoming** [comment]
I think all scenes that we want have been included - please reopen if not true.
