### ISSUE TITLE
SceneNav styling

### ISSUE THREAD

**Issue by johanne-aarup-hansen** [mirroringplaces/mirroringplaces.online#71]
Hej Balder

Jeg kunne godt tænke mig at redigere både indhold og udseende på sceneNav, men jeg ved ikke hvor jeg gør det?
Ja, der er forskellige ting som jeg gerne vil redesigne, så det er nemmest hvis jeg selv kan gøre det.

Vh Johanne

**Comment by johanne-aarup-hansen** [comment]
The End har også en forkert font...

**Comment by benjaoming** [comment]
Navigationen er defineret i /themes/mirroringplaces/layouts/chapters/single.html

https://github.com/mirroringplaces/mirroringplaces.online/blob/main/themes/mirroringplaces/layouts/chapters/single.html

**Comment by johanne-aarup-hansen** [comment]
Hov er det ikke den mappe du har flyttet? Den er der i hvert fald ikke umiddelbart...Kan du fortælle mig hvor den nu er?

**Comment by benjaoming** [comment]
jo, den hedder  /themes/mirroringplaces/layouts/maps/single.html nu :upside_down_face:

**Comment by johanne-aarup-hansen** [comment]
Nu har jeg stylet lidt, men det jeg gerne vil kan jeg ikke rigtig finde ud af. Jeg vil gerne have underline på kapitlerne, men ikke rækken af symboler.

Derudover er der stadig nogle småting med sceneNav som kunne være rart at få rettet:

1. For hver kapitel skal rækken med symboler følge kapitles symbol.
2. På de danske sider skal kapitlerne ikke hedde chapter, men kapitler
3. Underline på chaptersne i sceneNav, men ikke på rækken af symboler

**Comment by benjaoming** [comment]
> På de danske sider skal kapitlerne ikke hedde chapter, men kapitler

Det ligner at du har fikset det?
