### ISSUE TITLE
pop-up felt på kortet på mobilen

### ISSUE THREAD

**Issue by johanne-aarup-hansen** [mirroringplaces/mirroringplaces.online#78]
Hej
Har lige glemt denne her.
Jeg har ikke skrevet teksterne endnu, men tænker det er pop-up tekstkboxe ala tekstbox på storyen...
Giver det mening?
Ellers en ny side
Hvad tænekr du?

**Comment by benjaoming** [comment]
Det er allerede implementeret som en ny side; men måske funktionaliteten "røg i svinget" da vi lavede om på kortet mv

**Comment by benjaoming** [comment]
In order to test the new pages on a desktop computer:

1) navigate to the map
2) Then switch to mobile view (ctrl+shift+m on my computer)
3) Use a smartphone from the drop down

![image](https://github.com/mirroringplaces/mirroringplaces.online/assets/374612/edb9b67c-dcd3-4338-bd2b-299c8333c35b)

**Comment by benjaoming** [comment]
I have prepared it so that instructions can be added for each chapter. I imagine that a little snippet of the map or a photo of what to look for could be helpful.

**Comment by benjaoming** [comment]
Tested again to make sure, and it works :)
