### ISSUE TITLE
colors and symbols 

### ISSUE THREAD

**Issue by rodrigoandreolli** [mirroringplaces/mirroringplaces.online#80]
the shapes that indicate the sculptures in the map and their colors could be adjusted to the ones that are being installed in the space:  

- what is now the blue round change to orange color and stay in the same patio (adjust more precicsely the place where it sits in the map.
- the inverted traingle changes to pink  and changes places with the X one. (also needs to be better adjusted in the map)
- the X changes places with the inverted triangle. ( it also needs better placement) - the X I think is not the best symol for this one, I would suggest something closer to what was being used before, somehting that ressembles a Y or a λ but not exactly.

(the colors to the chapters have been suggested already in the organization of
![IMG_0082](https://github.com/mirroringplaces/mirroringplaces.online/assets/170082689/c4cac3f8-202b-4a8a-91e1-5d679a87ba4d)
 the Google sheet with the chapters and scenes list)

the positions we are now very defined as the sculpteres are installed.

**Comment by benjaoming** [comment]
Is there any possibility to adjust the lime color? It's very hard to see/read on a white background. I experimented earlier with adding a bit of shade around icons and text which can also work.
