### ISSUE TITLE
color of each chapter within other chapters

### ISSUE THREAD

**Issue by rodrigoandreolli** [mirroringplaces/mirroringplaces.online#81]
the indication of each chapter should always appear in its own color, helps navigation. beggining and end perhaps in blue 
![IMG_0081](https://github.com/mirroringplaces/mirroringplaces.online/assets/170082689/f213eca3-54bf-4600-80bd-767424a328eb)

**Comment by benjaoming** [comment]
This is fixed - except it's maybe possible to say that the menu could also have different colors, although it's also nice that it has the current chapter's.
